name: pint

on:
  push:
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - run: composer update --no-interaction --no-scripts
      - run: vendor/bin/pint --test
